/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package graphservice.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ServiceEnum implements org.apache.thrift.TEnum {
  CREATE_VERTICE(0),
  DELETE_VERTICE(1),
  UPDATE_VERTICE(2),
  READ_VERTICE(3),
  CREATE_ARESTA(4),
  DELETE_ARESTA(5),
  UPDATE_ARESTA(6),
  READ_ARESTA(7),
  LIST_VERTICES_ARESTA(8),
  LIST_ARESTAS_VERTICE(9),
  LIST_NEIGHBORS(10),
  LIST_VERTICES(11),
  LIST_ARESTAS(12);

  private final int value;

  private ServiceEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ServiceEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return CREATE_VERTICE;
      case 1:
        return DELETE_VERTICE;
      case 2:
        return UPDATE_VERTICE;
      case 3:
        return READ_VERTICE;
      case 4:
        return CREATE_ARESTA;
      case 5:
        return DELETE_ARESTA;
      case 6:
        return UPDATE_ARESTA;
      case 7:
        return READ_ARESTA;
      case 8:
        return LIST_VERTICES_ARESTA;
      case 9:
        return LIST_ARESTAS_VERTICE;
      case 10:
        return LIST_NEIGHBORS;
      case 11:
        return LIST_VERTICES;
      case 12:
        return LIST_ARESTAS;
      default:
        return null;
    }
  }
}
