/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author root
 */

import javax.swing.JOptionPane;
import graphservice.Graph;
import graphservice.Aresta;

import org.apache.thrift.TException;
import org.apache.thrift.transport.TTransport;
import org.apache.thrift.transport.TSocket;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.protocol.TBinaryProtocol;

public class TelaConsultarAresta extends javax.swing.JInternalFrame {

    private Graph.Client client;
    private int id;
    /**
     * Creates new form TelaConsultarAresta
     */
    public TelaConsultarAresta(int id, Graph.Client client) {
	this.client = client;
	this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Verificar Amizade");

        jLabel1.setText("ID Pessoa");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            Aresta a1 = this.client.readAresta(id,Integer.parseInt(jTextField1.getText()));
	    Aresta a2 = this.client.readAresta(Integer.parseInt(jTextField1.getText()),id);
	
	    if(a1 != null || a2 != null) {

		if(a1 != null) {

			JOptionPane.showMessageDialog(null,"Amizade encontrada com sucesso: \n" + "Pessoa 1: " + a1.pessoa1 + "\n" + "Pessoa 2: " + a1.pessoa2 + "\n"
            + "Distancia: " + a1.distancia + "\n" + "Descricao " + a1.descricao);

		}

		else if(a2 != null) {

			JOptionPane.showMessageDialog(null,"Amizade encontrada com sucesso: \n" + "Pessoa 1: " + a2.pessoa1 + "\n" + "Pessoa 2: " + a2.pessoa2 + "\n"
            + "Distancia: " + a2.distancia + "\n" + "Descricao " + a2.descricao);

		}

	    }

        } catch (TException ex) {
            System.out.println(ex);
        } 
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}

