/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import graphservice.Graph;
import graphservice.Vertice;
import graphservice.Aresta;

import org.apache.thrift.TException;
import org.apache.thrift.transport.TTransport;
import org.apache.thrift.transport.TSocket;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.protocol.TBinaryProtocol;

/**
 *
 * @author root
 */
public class TelaMenorCaminho extends javax.swing.JInternalFrame {

    private Graph.Client client;
    private int id;
    /**
     * Creates new form TelaMenorCaminho
     */
    public TelaMenorCaminho(int id, Graph.Client client) {
        this.client = client;
	this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Viagem");

        jLabel1.setText("ID Amigo");

        jButton1.setText("Menor Caminho");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

	List<Vertice> caminho;
	String pes = "";
	String cam = "";
	int distancia = 0;

	try {
            caminho = this.client.menorCaminho(id,Integer.parseInt(jTextField1.getText()));

	    if(caminho != null){

                    pes += "Pessoas Recomendadas\n";
		    cam += "Menor Caminho Conhecido\n";

                    for(int i=0; i<caminho.size(); i++) {
		
			if(i >= 1) {                        

				Vertice vert = caminho.get(i);
				Vertice vert2 = caminho.get(i-1);
				pes += "\n";
				pes += vert.nome;
			        pes += " - ";
				pes += vert.cidade_atual;
				cam += "\n";
			        cam += vert.cidade_atual;
				Aresta a = this.client.readAresta(vert.id, vert2.id);
				distancia += a.distancia;
		        }
                    }
		   
		    cam += "\n\nDistancia Total = " + distancia;
                    JOptionPane.showMessageDialog(null,cam);
		    JOptionPane.showMessageDialog(null,pes);
            }
            else{
                JOptionPane.showMessageDialog(null,"Caminho não existe");
            }

        } catch (TException ex) {
            System.out.println(ex);
        }        

    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}

